# Generated by Django 6.0.2 on 2026-02-27 11:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attempt',
            options={'ordering': ['-finished_at'], 'verbose_name': 'Попытка', 'verbose_name_plural': 'Попытки'},
        ),
        migrations.AlterModelOptions(
            name='attemptanswer',
            options={'verbose_name': 'Ответ в попытке', 'verbose_name_plural': 'Ответы в попытках'},
        ),
        migrations.AlterModelOptions(
            name='exam',
            options={'ordering': ['title'], 'verbose_name': 'Экзамен', 'verbose_name_plural': 'Экзамены'},
        ),
        migrations.AlterModelOptions(
            name='option',
            options={'ordering': ['question_id', 'order', 'id'], 'verbose_name': 'Вариант ответа', 'verbose_name_plural': 'Варианты ответов'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['exam_id', 'order', 'id'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterField(
            model_name='attempt',
            name='correct_count',
            field=models.PositiveIntegerField(verbose_name='Правильных ответов'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='duration_seconds',
            field=models.PositiveIntegerField(default=0, verbose_name='Время (сек)'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='attempts', to='exams.exam', verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='finished_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Окончание прохождения'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='score',
            field=models.PositiveIntegerField(verbose_name='Результат (%)'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='started_at',
            field=models.DateTimeField(verbose_name='Начало прохождения'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='total_questions',
            field=models.PositiveIntegerField(verbose_name='Всего вопросов'),
        ),
        migrations.AlterField(
            model_name='attempt',
            name='user_name',
            field=models.CharField(db_index=True, max_length=100, verbose_name='Имя пользователя'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='attempt',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='exams.attempt', verbose_name='Попытка'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Ответ верный'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='exams.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='attemptanswer',
            name='selected_option',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='exams.option', verbose_name='Выбранный вариант'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='description',
            field=models.TextField(blank=True, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='duration_minutes',
            field=models.PositiveIntegerField(default=20, verbose_name='Длительность (мин)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='passing_score',
            field=models.PositiveIntegerField(default=70, verbose_name='Порог прохождения (%)'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='subject',
            field=models.CharField(max_length=100, verbose_name='Направление'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='exam',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AlterField(
            model_name='option',
            name='is_correct',
            field=models.BooleanField(default=False, verbose_name='Правильный ответ'),
        ),
        migrations.AlterField(
            model_name='option',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='option',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='exams.question', verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='option',
            name='text',
            field=models.CharField(max_length=300, verbose_name='Текст варианта'),
        ),
        migrations.AlterField(
            model_name='question',
            name='difficulty',
            field=models.CharField(choices=[('easy', 'Легкий'), ('medium', 'Средний'), ('hard', 'Сложный')], default='medium', max_length=10, verbose_name='Сложность'),
        ),
        migrations.AlterField(
            model_name='question',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='exams.exam', verbose_name='Экзамен'),
        ),
        migrations.AlterField(
            model_name='question',
            name='order',
            field=models.PositiveIntegerField(default=1, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='question',
            name='prompt',
            field=models.TextField(verbose_name='Вопрос'),
        ),
        migrations.AlterField(
            model_name='question',
            name='topic',
            field=models.CharField(max_length=100, verbose_name='Тема'),
        ),
    ]
