# Generated by Django 6.0.2 on 2026-02-28 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_alter_attempt_options_alter_attemptanswer_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attempt',
            name='max_scoring_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Макс. скоринговый балл'),
        ),
        migrations.AddField(
            model_name='attempt',
            name='scoring_points',
            field=models.PositiveIntegerField(default=0, verbose_name='Скоринговый балл'),
        ),
        migrations.AddField(
            model_name='question',
            name='explanation',
            field=models.TextField(blank=True, verbose_name='Пояснение для разбора'),
        ),
        migrations.AddField(
            model_name='question',
            name='score_value',
            field=models.PositiveIntegerField(default=1, verbose_name='Баллы за вопрос'),
        ),
    ]
