# Generated by Django 5.2.6 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0003_attempt_max_scoring_points_attempt_scoring_points_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='subject_color',
            field=models.CharField(default='#2563eb', max_length=7, verbose_name='Цвет темы'),
        ),
    ]

