# Generated by Django 6.0.2 on 2026-02-28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_exam_subject_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='default_question_time_sec',
            field=models.PositiveIntegerField(blank=True, help_text='Если у вопроса не задано время, будет использовано это значение.', null=True, verbose_name='Время на вопрос по умолчанию (сек)'),
        ),
        migrations.AddField(
            model_name='question',
            name='time_limit_sec',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Время на вопрос (сек)'),
        ),
    ]
