# Generated by Django 5.2.12 on 2026-03-12 08:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quests', '0002_seed_default_quests'),
    ]

    operations = [
        migrations.AddField(
            model_name='quest',
            name='requires_approval',
            field=models.BooleanField(default=False, verbose_name='Требует проверки'),
        ),
        migrations.AddField(
            model_name='quest',
            name='requires_proof',
            field=models.BooleanField(default=False, verbose_name='Нужен скриншот/фото'),
        ),
        migrations.CreateModel(
            name='DutyAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duty_type', models.CharField(choices=[('cleaning', 'Уборка')], db_index=True, default='cleaning', max_length=20, verbose_name='Тип')),
                ('business_date', models.DateField(db_index=True, verbose_name='Дата')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='duties', to='quests.employee')),
            ],
            options={
                'verbose_name': 'Дежурство',
                'verbose_name_plural': 'Дежурства',
                'ordering': ['-business_date', 'duty_type'],
                'constraints': [models.UniqueConstraint(fields=('duty_type', 'business_date'), name='uniq_duty_by_date')],
            },
        ),
        migrations.CreateModel(
            name='QuestSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('business_date', models.DateField(db_index=True, verbose_name='Дата (ключ)')),
                ('status', models.CharField(choices=[('pending', 'На проверке'), ('approved', 'Одобрено'), ('rejected', 'Отклонено')], db_index=True, default='pending', max_length=10, verbose_name='Статус')),
                ('proof_image', models.ImageField(blank=True, null=True, upload_to='quest_proofs/%Y/%m/%d/', verbose_name='Скриншот/фото')),
                ('notes', models.TextField(blank=True, default='', verbose_name='Комментарий')),
                ('review_comment', models.TextField(blank=True, default='', verbose_name='Комментарий проверяющего')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверено')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quest_submissions', to='quests.employee')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='submissions', to='quests.quest')),
            ],
            options={
                'verbose_name': 'Отправка на проверку',
                'verbose_name_plural': 'Отправки на проверку',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'pending')), fields=('quest', 'employee', 'business_date'), name='uniq_pending_quest_submission')],
            },
        ),
    ]
